baseURL = 'https://cu.harrycresswell.com/'
languageCode = 'en-gb'
title = 'cu.css'
theme = "cu"

[params]
site_description = 'A lightweight CSS framework'
site_keywords = ""
site_image = ""

[params.author]
name = "Harry Cresswell"
github = "https://github.com/harrycresswell"
linkedin = "https://linkedin.com/in/harrycresswell/"

# Allow HTML in markdown (use with caution)
[markup.goldmark.renderer]
unsafe = true
