baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'cu.css'
theme = "cu"

[params]
description = 'A modern SCSS framework'

# Allow HTML in markdown (use with caution)
[markup.goldmark.renderer]
unsafe = true
